TCVP-2136 mapping for disputant update request
bcgov/jag-traffic-courts-online pull request #1009
Opened 2023-02-06 21:04 UTC by karahanb

# Description

This PR includes the following proposed change(s):

- [TCVP-2136](https://justice.gov.bc.ca/jira/browse/TCVP-2136)
- Added mapper for `DisputeUpdateRequest` and updated occm-openapi-spec in order to map ORDS data to Oracle Data API disputeUpdateRequest model and vice versa.
- Updated Oracle Data API OpenAPI spec client and refactored `DisputantUpdateRequest` into `DisputeUpdateRequest`.
- Added JUnit tests for the mapper.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

mvn verify

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

2023-02-06 21:16 UTC, karahanb commented
@lfdgov Can you please confirm whether the renaming `DisputantUpdateRequest` to `DisputeUpdateRequest` will break frontend or not? If there is a dependency on that naming we should update front-end as well.

2023-02-06 23:14 UTC, KDNeufeld commented on src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestRejectedConsumer.cs
> +using DisputantUpdateRequest = TrafficCourts.Common.OpenAPIs.OracleDataApi.v1_0.DisputeUpdateRequest;
If you're renaming DisputantUpdateRequest to DisputeUpdateRequest, should this `using` statement be updated as well to be consistent?

```suggestion
using DisputeUpdateRequest = TrafficCourts.Common.OpenAPIs.OracleDataApi.v1_0.DisputeUpdateRequest;
```

2023-02-06 23:16 UTC, KDNeufeld commented on src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestAcceptedConsumer.cs
>  namespace TrafficCourts.Workflow.Service.Consumers;
This class DisputantUpdateRequestAcceptedConsumer should be updated to DisputeUpdateRequestAcceptedConsumer to be consistent

2023-02-06 23:22 UTC, KDNeufeld commented on src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeUpdateRequestMapper.java
> +	}
Both of these code mappers can be simplified by just using the interface.


```
	@Named("mapShortNamedEnum")
	default String mapShortNamedEnum(ShortNamedEnum code) {
		return code.getShortName();
	}
```

2023-02-06 23:24 UTC, KDNeufeld commented on src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Auditable.java
> +	@TypeDef(name = "disputantUpdateStatus", defaultForType = DisputeUpdateRequestStatus.class, typeClass = ShortNamedEnumType.class),
```suggestion
	@TypeDef(name = "disputeUpdateRequestStatus", defaultForType = DisputeUpdateRequestStatus.class, typeClass = ShortNamedEnumType.class),

```

2023-02-06 23:29 UTC, KDNeufeld approved these changes
Great work. 
As Lorraine mentioned, confirm the UI is not affected by the refactoring name change.
There are still quite a few references to the word "DisputantUpdateRequest" in the .NET and oracle-data-api code bases. If we're going to refactor the name, lets go all the way.

2023-02-07 14:50 UTC, karahanb commented
> Great work. As Lorraine mentioned, confirm the UI is not affected by the refactoring name change. There are still quite a few references to the word "DisputantUpdateRequest" in the .NET and oracle-data-api code bases. If we're going to refactor the name, lets go all the way.

Thanks for catching those remaining "DisputantUpdateRequest" references. I fixed all the ones that were causing errors but should have done some more extensive search. I will fix the remaining ones. Actually I asked Lorraine to confirm the UI is not affected since I'm not that familiar with frontend code but I will check that as well.

2023-02-07 16:24 UTC, KDNeufeld approved these changes
Great work! Refactoring looks good.

2023-02-07 16:32 UTC, lfdgov requested changes
update apis in client side source code

2023-02-07 19:37 UTC, lfdgov requested changes

2023-02-07 19:37 UTC, lfdgov commented on src/frontend/citizen-portal/package.json
> -    "@angular/cli": "^14.2.10",
change this back to 14.2.10 in package.json and then do yarn install

2023-02-07 19:58 UTC, lfdgov approved these changes

2023-02-07 20:21 UTC, merged