TCVP-2239 Staff portal fix email resend verification
bcgov/jag-traffic-courts-online pull request #1082
Opened 2023-03-08 19:45 UTC by karahanb

# Description

This PR includes the following proposed change(s):

- [TCVP-2239](https://justice.gov.bc.ca/jira/browse/TCVP-2239)
- Fixed the not being able to resend email verification from staff portal issue by publishing the correct message.
- Removed the unnecessary EmailVerificationSend message.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Ran the apps through docker and clicked on the resend email verification button in staff portal and confirmed the email verification email has been received.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

2023-03-08 21:27 UTC, KDNeufeld approved these changes
Glad you were able to track this down. Great work.

2023-03-08 23:26 UTC, lfdgov approved these changes

2023-03-09 00:06 UTC, lfdgov requested changes
please test more these changes do not appear to result in an email being sent

2023-03-09 13:52 UTC, karahanb commented
> please test more these changes do not appear to result in an email being sent

I tested this couple of times on my local and worked perfectly for me. Can you please specify your test steps for your failure case? There might be something out of sync on your local dev environment.

2023-03-09 17:37 UTC, lfdgov approved these changes

2023-03-09 17:40 UTC, merged