ActRegCode is not a valid VT2 property and so may be undefined.
bcgov/jag-traffic-courts-online pull request #1335
Opened 2023-10-23 22:02 UTC by KDNeufeld

# Description

This PR includes the following proposed change(s):

Fixed NPE in Staff Portal

The Staff Portal would not load VT2 images due to a mismatch of properties, namely the `act_or_regulation_name_code` field is only on VT1 images, not VT2. There is no such property on VT2 images called `act_or_regulation_name_code` and so this field may be undefined.

Note: I noticed that the Staff Portal may try to use this field for determining if the Count sections are valid or not (presumbably to pull the "MVA" text for the act portion of the Act/Sect/Desc fields. Currently the portal thinks the counts are always invalid.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [ ] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

2023-10-23 23:26 UTC, Sharkww requested changes
count number is not correct

2023-10-23 23:26 UTC, Sharkww commented on src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
> +          if (!foundViolationTicketCount2[0].actOrRegulationNameCode) foundViolationTicketCount2[0].actOrRegulationNameCode = ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"
count_no_2

2023-10-23 23:26 UTC, Sharkww commented on src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
> +            actOrRegulationNameCode: ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"] ? ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"].value : ""
same as above

2023-10-23 23:26 UTC, Sharkww commented on src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
> +          if (!foundViolationTicketCount3[0].actOrRegulationNameCode) foundViolationTicketCount3[0].actOrRegulationNameCode = ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"
same as above

2023-10-23 23:26 UTC, Sharkww commented on src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
> +            actOrRegulationNameCode: ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"] ? ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"].value : ""
same as above

2023-10-23 23:31 UTC, KDNeufeld commented on src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
> +            actOrRegulationNameCode: ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"] ? ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"].value : ""
Excellent catch. Silly cut n' paste.

2023-10-23 23:35 UTC, Sharkww reviewed
Just asking which part was showing 'undefined' because it should be showing "" in frontend already if is null or undefined

2023-10-23 23:38 UTC, KDNeufeld commented
> Just asking which part was showing 'undefined' because it should be showing "" in frontend already if is null or undefined

The `ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"]` field is undefined for VT2 images so the `.value` was throwing an error.

2023-10-23 23:42 UTC, KDNeufeld commented on src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
> +          if (!foundViolationTicketCount2[0].actOrRegulationNameCode) foundViolationTicketCount2[0].actOrRegulationNameCode = ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"
Excellent catch. Silly cut n' paste.

2023-10-23 23:42 UTC, KDNeufeld commented on src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
> +          if (!foundViolationTicketCount3[0].actOrRegulationNameCode) foundViolationTicketCount3[0].actOrRegulationNameCode = ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"
Excellent catch. Silly cut n' paste.

2023-10-23 23:42 UTC, KDNeufeld commented on src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
> +            actOrRegulationNameCode: ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"] ? ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"].value : ""
Excellent catch. Silly cut n' paste.

2023-10-23 23:43 UTC, Sharkww commented
ok, can you try `ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"]?.value` ? Thanks

2023-10-24 15:12 UTC, KDNeufeld commented
> ok, can you try `ocrViolationTicket.fields["counts.count_no_1.act_or_regulation_name_code"]?.value` ? Thanks

That's much cleaner, thanks. Done.

2023-10-24 22:38 UTC, Sharkww approved these changes

2023-10-24 22:40 UTC, merged