Feature/tcvp 3030 springboot updates
bcgov/jag-traffic-courts-online pull request #1980
Opened 2024-10-15 16:29 UTC by jianmingtu

# Description

This PR includes the following proposed change(s):

- {List all the changes, if possible add the jira ticket #}

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [ ] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

2024-10-15 21:24 UTC, jianmingtu reviewed
Update Java from 11 to 17;  Springboot from 2.7.4 to 3.3.4
 Fixed the 24 high/critical vulnerabilities, see result, [vulnerabilities_after.txt](https://jag.gov.bc.ca/jira/secure/attachment/152079/152079_vulnerabilities_after.txt)
 Remove the H2 database from code base because we only use ORDS to fetch and update data
 Comment out the previous H2 unit tests because we are not connecting H2 database now, plus unit tests using H2 database are integration tests.
 Add these four files for unit testing EmailHistory in Controller, Reposition, Service and OutgoingEmailMapper.  This will be a sample patten if we need to unit test other ControllerReposition./Service/Mapper.
EmailHistory
├── EmailHistoryControllerTest.java
├── EmailHistoryRepositoryTest.java
├── EmailHistoryServiceTest.java
└── OutgoingEmailMapperTest.java

2024-10-16 21:20 UTC, karahanb requested changes
This is great work! All main functionalities work as expected with the upgraded libraries except the Redis connection when all services are started by docker compose. I get the following error: `org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis.` This might be a side effect of one of the updated libraries in pom since I could not see any code changes around the redis connection configuration or lookup service. 

Also, there are some useful test which are commented out could have kept since they are unrelated to H2 database and provide some unit and integration test coverage through either connecting to ORDS or mocking some services. I suggest to re-enable those tests that I individually commented on by isolating them from the H2 stuff in BaseTestSuite.

2024-10-16 21:20 UTC, karahanb commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapperTest.java
You could have kept this mapper test as this is unrelated to H2 database.

2024-10-16 21:20 UTC, karahanb commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeUpdateRequestMapperTest.java
We should keep this test as well.

2024-10-16 21:20 UTC, karahanb commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java
We should keep this test as well.

2024-10-16 21:20 UTC, karahanb commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/OutgoingEmailMapperTest.java
We should keep this test as well.

2024-10-16 21:20 UTC, karahanb commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapperTest.java
We should keep this test as well.

2024-10-16 21:20 UTC, karahanb commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsOccamTest.java
We can keep this test as well as it actually uses ORDS for creating the test records and deletes at the end of the test if the test is enabled.

2024-10-16 21:20 UTC, karahanb commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsTcoTest.java
Same for this test. It uses ORDS.

2024-10-16 21:20 UTC, karahanb commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
We should keep this test as well.

2024-10-16 21:20 UTC, karahanb commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java
We should keep this test as well.

2024-10-22 16:02 UTC, jianmingtu commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapperTest.java
reenabled

2024-10-22 16:03 UTC, jianmingtu commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java
reenabled

2024-10-22 16:03 UTC, jianmingtu commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapperTest.java
reenabled

2024-10-22 16:03 UTC, jianmingtu commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsTcoTest.java
reenabled

2024-10-22 16:04 UTC, jianmingtu commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeUpdateRequestMapperTest.java
reenabled

2024-10-22 16:05 UTC, jianmingtu commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/OutgoingEmailMapperTest.java
reenabled

2024-10-22 16:07 UTC, jianmingtu commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsOccamTest.java
DisputeServiceOrdsOccamTest of the previous springboot 2 version failed so  I could not reenable to the old version

2024-10-22 16:08 UTC, jianmingtu commented on src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
reenabled

2024-10-23 13:54 UTC, karahanb approved these changes

2024-10-23 17:47 UTC, merged