WIP: TCVP-1424 Update JJ Dispute models as per wireframes
bcgov/jag-traffic-courts-online pull request #649
Opened 2022-07-07 21:02 UTC by karahanb

# Description

This PR includes the following proposed change(s):

- [TCVP-1424](https://justice.gov.bc.ca/jira/browse/TCVP-1424)
- Updated 'JJDispute' model and created new 'JJDisputedCount' and 'DisputantContactInformation' models and defined their entity relationships based on the latest JJ Workbench wireframes.
- Updated the data.sql script to populate JJDispute mock records based on the new fields.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

2022-07-08 16:03 UTC, lfdgov approved these changes

2022-07-08 23:32 UTC, Sharkww approved these changes

2022-07-08 23:43 UTC, lfdgov requested changes

2022-07-08 23:43 UTC, lfdgov commented on src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java
>  package ca.bc.gov.open.jag.tco.oracledataapi.model;
We also need the fine Reduction reason, the time to pay reason and the offence location as part of this model.  The reconciliation process should pull in the written reasons from our TCO database.  The offence location is on the written ticket as the 'At or near highway', 'at or near city/town' .  We currently do not get our OCR reader to scan this on the handwritten tickets though there is a spot for it.  We may need to follow up about this one in standup.

2022-07-08 23:43 UTC, lfdgov commented on src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java
>  package ca.bc.gov.open.jag.tco.oracledataapi.model;
I also added the C# changes to the staff-api and the client side changes to make this PR more complete.  Let me know when you have added the additional model fields for reasons and lets discuss the offence location with the business.

2022-07-11 18:37 UTC, lfdgov approved these changes

2022-07-11 18:42 UTC, merged